### ISSUE TITLE
DISCON_OC3Hywind.dll

### ISSUE THREAD

**Issue by PeterV310** [OpenFAST/openfast#363]
Can anyone provide a copy of the file DISCON_OC3Hywind.dll compiled for 64-bit applications so I can use it to run Test25 (5MW_OC4Semi_WSt_WavesWN) in openFAST?

Asking because I have not managed to compile openFAST yet ..

Thanks

**Comment by PeterV310** [comment]
So .. at the stage I managed to compile using VStudio .. However running Test25 I still recieve the error:

FAST_InitializeAll:SrvD_Init:BladedInterface_Init:The dynamic library
c:/OpenFAST_v2.1.0/windows_openfast_binaries/openfast_v2.1.0_binaries/r-test-master/r-test-master/
glue-codes/openfast/5MW_OC4Semi_WSt_WavesWN/../5MW_Baseline/ServoData/DISCON_OC3Hywind.dll could
not be loaded. Check that the file exists in the specified location and that it is compiled for
64-bit applications.

Any help please?

**Comment by jjonkman** [comment]
Is you DLL compiled in 64 bits and is it located at the specified path?

**Comment by PeterV310** [comment]
Not sure if compiled in 64 bits. Is there a way on how to check this? Where would the path be specified in the FAST files?

**Comment by rafmudaf** [comment]
The path to the controller is given in the ServoDyn input file. In your case, see this file:
https://github.com/OpenFAST/r-test/blob/master/glue-codes/openfast/5MW_OC4Semi_WSt_WavesWN/NRELOffshrBsline5MW_OC4DeepCwindSemi_ServoDyn.dat#L66

Also, make sure to read the docs, the note at the end of this section explains where the controller should be for the regression tests:
https://openfast.readthedocs.io/en/master/source/testing/regression_test.html#executing-with-python-driver

**Comment by PeterV310** [comment]
Thanks. Will check and revert if issue is closed.

**Comment by PeterV310** [comment]
Updated the path to the conroller and program works now.

Thanks a lot for your help.

**Comment by relhamoud** [comment]
@PeterV310 
Please could you tell what you did ? 
I'm facing the same problem

**Comment by relhamoud** [comment]
@PeterV310 
The problem is solved 😁

**Comment by cheng0672** [comment]
@rafmudaf 
I still can't solve this problem.
Please could you tell what you did ?

**Comment by shuilanjiaodashi** [comment]
Please could you tell what you did ? I'm facing the same problem

**Comment by jjonkman** [comment]
Dear @shuilanjiaodashi,

You can find a 64-bit precompiled Windows binary of _DISCON_OC3Hywind.dll_ (and other baseline controllers for the NREL 5-MW turbine) along with other OpenFAST-related binaries for Windows with each release here: https://github.com/OpenFAST/openfast/releases.

Best regards,

**Comment by shuilanjiaodashi** [comment]
thank you very much, i have solved this problem
